"""autogenerate template tables

Revision ID: 018e339ca18e
Revises: 3d06e6c30570
Create Date: 2026-03-12 11:56:20.296285

"""

import sqlalchemy as sa
from alembic import op

revision = '018e339ca18e'
down_revision = '3d06e6c30570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###