"""autogenerate template tables

Revision ID: 3d06e6c30570
Revises:
Create Date: 2026-03-11 20:24:11.042891

"""

import sqlalchemy as sa
from alembic import op

revision = "3d06e6c30570"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="templates",
    )
    op.create_index(
        op.f("ix_templates_template_deleted_at"),
        "template",
        ["deleted_at"],
        unique=False,
        schema="templates",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_templates_template_deleted_at"),
        table_name="template",
        schema="templates",
    )
    op.drop_table("template", schema="templates")
    # ### end Alembic commands ###
