"""init template module

Revision ID: f11acf9f9d9a
Revises:
Create Date: 2026-03-11 18:48:25.684374

"""

revision = "f11acf9f9d9a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
